name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  release:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
      - name: Set up Node
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci
      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: npm run build
      - name: Setup Pages
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/configure-pages@v5
      - name: Upload artifact
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        if: ${{ steps.release.outputs.release_created }}
        id: deployment
        uses: actions/deploy-pages@v4
